# Generated by Django 5.2 on 2025-04-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmaster',
            name='image_url',
        ),
    ]
