# Generated by Django 5.2 on 2025-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_category_grade_user_remove_cardinstance_card_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="updated_at",
            new_name="Year",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
