# Generated by Django 5.2 on 2025-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_rename_updated_at_category_year_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="Year",
            field=models.CharField(max_length=4),
        ),
    ]
